version: '3.7' # menggunakan docker compose versi 3.7

services:
  item-app:
    image: ghcr.io/gungindi/item-app:v1 # menggunakan image dari github packages
    ports:
      - "80:8080" # port mapping ke 80
    depends_on:
      - item-db # item-app hanya berjalan setelah item-db diluncurkan
    restart: always # container selalu restart jika terhenti

  item-db:
    image: mongo:3 # menggunakan image mongo:3 dari docker hub
    volumes:
      - app-db:/data/db # menggunakan volume bernama app-db dengan path /data/db pada container
    restart: always # container selalu restart jika terhenti

volumes:
  app-db: # membuat volumes bernama app-db
